const SIDE_BAR_OPEN_WIDTH = '300px';
const SIDE_BAR_CLOSE_WIDTH = '5rem';
const SIDE_BAR_HEIGHT = '100%';

const SIDE_BAR_BACKGROUND_COLOR = '#506EA5';
const SIDE_BAR_FONT_COLOR = '#323C73';
const SIDE_BAR_FONT_HOVER_COLOR = '#FFF';
const SIDE_BAR_BUTTON_COLOR = '#506EA5';
const SIDE_BAR_BUTTON_HOVER_COLOR = '#3C5087';
const SIDE_BAR_BUTTON_BOX_SHADOW_COLOR = '#1E3269';

export {
  SIDE_BAR_OPEN_WIDTH,
  SIDE_BAR_CLOSE_WIDTH,
  SIDE_BAR_BACKGROUND_COLOR,
  SIDE_BAR_FONT_COLOR,
  SIDE_BAR_FONT_HOVER_COLOR,
  SIDE_BAR_BUTTON_COLOR,
  SIDE_BAR_BUTTON_HOVER_COLOR,
  SIDE_BAR_HEIGHT,
  SIDE_BAR_BUTTON_BOX_SHADOW_COLOR,
};
